[BRE-101] Remove dept-devops from CODEOWNERS
bitwarden/sm-ansible pull request #38
Opened 2024-06-10 12:32 UTC by michalchecinski

## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/BRE-101

## 🚧 Type of change

-   🎂 Other

## 📔 Objective

Remove dept-devops from all CODEOWNERS, and add dept-bre to `.github/workflows/publish-to-galaxy.yml`.

Remove dept-devops from CODEOWNERS.

## 📋 Code changes

-   **.github/CODEOWNERS:** Remove dept-devops from all CODEOWNERS, and add dept-bre to `.github/workflows/publish-to-galaxy.yml`.

## ⏰ Reminders before review

-   Contributor guidelines followed
-   All formatters and local linters executed and passed
-   Written new unit and / or integration tests where applicable
-   Protected functional changes with optionality (feature flags)
-   Used internationalization (i18n) for all UI strings
-   CI builds passed
-   Communicated to DevOps any deployment requirements
-   Updated any necessary documentation or informed the documentation team

## 🦮 Reviewer guidelines

-   👍 (`:+1:`) or similar for great changes
-   📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
-   ❓ (`:question:`) for questions
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed
    issue and could potentially benefit from discussion
-   🎨 (`:art:`) for suggestions / improvements
-   ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
-   🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
-   ⛏ (`:pick:`) for minor or nitpick changes

2024-06-20 14:09 UTC, coltonhurst submitted a review, later dismissed

2024-10-16 18:17 UTC, vgrassia requested changes
Before this is merged in we need a TSD ticket opened to have `@bitwarden/dept-bre` added to this repository.

2024-10-16 18:17 UTC, vgrassia commented on .github/CODEOWNERS
> +# BRE for release workflow changes
```suggestion
## BRE team owns these workflows ##
```

2024-10-17 09:51 UTC, michalchecinski commented
TSD ticket created: https://bitwarden.atlassian.net/servicedesk/customer/portal/5/TSD-931

2024-10-18 15:20 UTC, coltonhurst reviewed
It says the codeowners file contains errors?

2024-10-21 13:07 UTC, vgrassia approved these changes

2024-10-21 19:53 UTC, coltonhurst approved these changes

2024-10-21 19:53 UTC, merged